name = "modrinth-resources-download"
author = "Dark2932"
version = "x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec88e58738aa6e65fea6f56c7ca1a9b6f436c297c4ff699c86ca4d52f40524e6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
