name = "modrinth-resources-download"
author = "Dark2932"
version = "x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e616679af48d83ded6b244333e027479ff584a7fef8dfb0b44a3eec5b1086e86"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
