name = "modrinth-resources-download"
author = "Dark2932"
version = "x"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ef5e6e96026d709e3ad72bbae7ef03390dba415c15b6736920769dde7d0b608"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
